config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  require "sidekiq-status/web"
  require "sidekiq/cron/web"
  # require "sidekiq/batch/web"

  mount Sidekiq::Web, at: "/sidekiq"
  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"

  resources :authentications
  resources :bookings
  resources :rooms

  get "login", to: "authentications#login", as: :login
  post "auth/login", to: "authentications#server_login"
  get "logout", to: "authentications#logout", as: :logout

  get "available_rooms", to: "rooms#available_rooms", as: :available_rooms
  get "occupied_rooms", to: "rooms#occupied_rooms", as: :occupied_rooms
  get "checkin", to: "rooms#check_in", as: :check_in
  post "server_checkin", to: "rooms#server_check_in"
  get "checkout", to: "rooms#check_out", as: :check_out
  get "bulk_checkin", to: "rooms#bulk_check_in", as: :bulk_check_in

  get "room_booking", to: "bookings#room_booking", as: :room_booking
  post "room_booking", to: "bookings#server_booking", as: :server_booking

  get "profile", to: "authentications#profile", as: :profile

  # reports routes
  get "bills_reports", to: "reports#bills_reports", as: :bills_reports
  get "checkin_reports", to: "reports#checkin_reports", as: :checkin_reports
  get "checkout_reports", to: "reports#checkout_reports", as: :checkout_reports
  get "transfers_reports", to: "reports#transfers_reports", as: :transfers_reports
  get "complaints_reports", to: "reports#complaints_reports", as: :complaints_reports
  get "accomodation_reports", to: "reports#accomodation_reports", as: :accomodation_reports
  get "resources_reports", to: "reports#resources_reports", as: :resources_reports

  # get "booking", to: "bookings#bookings"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "dashboards#index"
  get "/", to: "dashboards#index", as: :dashboard
end

app/models/authentication.rb
class Authentication < ApplicationRecord
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  before_action :set_authentication, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /authentications or /authentications.json
  def index
    @authentications = Authentication.all
  end

  # GET /authentications/1 or /authentications/1.json
  def show
  end

  # GET /authentications/new
  def new
    @authentication = Authentication.new
  end

  # GET /authentications/1/edit
  def edit
  end

  # POST /authentications or /authentications.json
  def create
    @authentication = Authentication.new(authentication_params)

    respond_to do |format|
      if @authentication.save
        format.html { redirect_to @authentication, notice: "Authentication was successfully created." }
        format.json { render :show, status: :created, location: @authentication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authentications/1 or /authentications/1.json
  def update
    respond_to do |format|
      if @authentication.update(authentication_params)
        format.html { redirect_to @authentication, notice: "Authentication was successfully updated." }
        format.json { render :show, status: :ok, location: @authentication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  def login
    # byebug

  end

  def server_login
    begin
      puts server_login_params
      # byebug
      # byebug
      url = URI("https://bookinn.ngrok.io/auth/login")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Post.new(url)
      request["Content-Type"] = "application/json"
      request.body = server_login_params.to_json
      response = http.request(request)
      puts response.read_body

      @response_json = JSON.parse(response.read_body)
    rescue ActiveRecord::RecordNotFound
    else
      if @response_json["status"] == 200
        # create session
        session['user_id'] = @response_json["data"]['id']
        session["access_token"] = @response_json["access_token"]
        session["username"] = @response_json["data"]["username"]
        session["role_id"] = @response_json["data"]["role_id"]
        session["hotel_id"] = @response_json["data"]["hotel_id"]
        session["email"] = @response_json["data"]["email"]
        redirect_to dashboard_path
      else
        # login failed
        redirect_to login_path
      end
    end
  end

  def logout
    reset_session
    redirect_to login_path
  end 

  def profile
  end

  # DELETE /authentications/1 or /authentications/1.json
  def destroy
    @authentication.destroy
    respond_to do |format|
      format.html { redirect_to authentications_url, notice: "Authentication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_authentication
    @authentication = Authentication.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def authentication_params
    params.fetch(:authentication, {})
  end

  def server_login_params
    params.permit(:email, :password)
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= form_with(model: authentication) do |form| %>
  <% if authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
        <% authentication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing Authentication</h1>

<%= render 'form', authentication: @authentication %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authentications</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authentications.each do |authentication| %>
      <tr>
        <td><%= link_to 'Show', authentication %></td>
        <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
        <td><%= link_to 'Destroy', authentication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/login.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel='icon' href='demo/img/.png' type='image/x-icon'/ >
    <title>Reception Desk</title>

    <!-- icon fonts -->

    <link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_1.css">
    <link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_2.css">
    <link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_3.css">
    <link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_4.css">
    <link rel="stylesheet" href="http://cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css">

    <!-- Vendor styles -->
    <link rel="stylesheet" href="assets/vendors/OwlCarousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="assets/vendors/OwlCarousel/assets/owl.theme.default.css">
    <link rel="stylesheet" href="assets/css/flaticon-font/flaticon.css">

    <link rel="stylesheet" href="assets/vendors/material-design-iconic-font/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="assets/vendors/animate.css/animate.min.css">
    <link rel="stylesheet" href="assets/vendors/jquery-scrollbar/jquery.scrollbar.css">
    <link rel="stylesheet" href="assets/vendors/fullcalendar/fullcalendar.min.css">
    <link rel="stylesheet" href="assets/vendors/select2/css/select2.min.css">
    <link rel="stylesheet" href="assets/vendors/bootstrap-select/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="assets/vendors/dropzone/dropzone.css">
    <link rel="stylesheet" href="assets/vendors/nouislider/nouislider.min.css">
    <link rel="stylesheet" href="assets/vendors/trumbowyg/ui/trumbowyg.min.css">
    <link rel="stylesheet" href="assets/vendors/flatpickr/flatpickr.min.css" />
    <link rel="stylesheet" href="assets/vendors/rateyo/jquery.rateyo.min.css">
    <link rel="stylesheet" href="assets/vendors/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">

    <!-- App styles -->
    <link rel="stylesheet" href="assets/css/app.min.css">
    <link rel="stylesheet" href="assets/css/daterangepicker.css">

    <style>
    .login-img-container img{
 height: 300px;
}

.login-img-container{
    display: flex;
    justify-content: flex-start;
    align-items: flex-end;
}

.btn-login{
    display: block;
    width: 100%;
    height: calc(3.25rem + 2px);
    padding: .375rem .2rem;
    font-size: 1rem;
    line-height: 1.5;
    color: white;
    background-color: #d76713;
    background-clip: padding-box;
    border-radius: 0;
    transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out
}

.login-form-header{
    display: flex;
    align-items: center;
    flex-direction: column;
    margin-bottom: 40px;
}

.login-content{
    height: 100vh;
    background: white;
    display: flex;
    padding: 4rem;
    flex-direction: row;
    justify-content: center;
    align-items: center;
}

.login-form{
    padding: 6rem 5rem !important;
    border: 1px solid #80808052;
    border-radius: 7px;
}

.the-login-logo{
    height: 50px;
    margin-bottom: 20px;
}
    </style>

</head>

<body data-ma-theme="green">
    <main class="main">
        <div class="page-loader">
            <div class="page-loader__spinner">
                <svg viewBox="25 25 50 50">
                    <circle cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
                </svg>
            </div>
            <span class="powerd-container">
                <strong>A product of</strong>
                <img src="assets/demo/img/logo-files/nouveta_logo.png">
            </span>
        </div>

        <section class="">
            <div class="login-content col-12">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-6 d-flex justify-content-center pr-2">
                        <span class="login-img-container">
                            <img src="assets/demo/img/bg/hotel-checkin.jpg">
                        </span>
                    </div>

                    <div class="col-sm-12 col-md-12 col-lg-6">
                        <%= form_with url: "auth/login", method: :post, class: "login-form" do |form| %>
                            <div class="login-form-header p-1">
                                <a class="" href="index.html"><img class="the-login-logo" src="assets/demo/img/logo-files/bookinn.png"></a>
                                <h2 class="mb-2">Login Page</h2>
                                <small>Fill in the information below to get access to the bookinn dashboard</small>
                            </div>
                            <div class="form-group"> 
                                <label>
                                    <strong>Email</strong>  <strong class="text-danger">*</strong>
                                </label>                                                            
                                <input type="text" class="form-control" placeholder="Enter your email address" name="email" required>
                            </div>

                            <div class="form-group"> 
                                <label>
                                    <strong>Password</strong>  <strong class="text-danger">*</strong>
                                </label>                                                            
                                <input type="password" class="form-control" placeholder="Enter your password" name="password" required>
                            </div>

                            <div class="form-group"> 
                                <button class="btn btn-primary btn-login">LOGIN</button>
                            </div>
                        <% end %>
                        <form class="login-form d-none">
                            <div class="login-form-header p-1">
                                <a class="" href="index.html"><img class="the-login-logo" src="assets/demo/img/logo-files/bookinn.png"></a>
                                <h2 class="mb-2">Login Page</h2>
                                <small>Fill in the information below to get access to the bookinn dashboard</small>
                            </div>
                            <div class="form-group"> 
                                <label>
                                    <strong>Email</strong>  <strong class="text-danger">*</strong>
                                </label>                                                            
                                <input type="text" class="form-control" placeholder="Enter your email address" name="email" required>
                            </div>

                            <div class="form-group"> 
                                <label>
                                    <strong>Password</strong>  <strong class="text-danger">*</strong>
                                </label>                                                            
                                <input type="text" class="form-control" placeholder="Enter your password" name="password" required>
                            </div>

                            <div class="form-group"> 
                                <button class="btn btn-primary btn-login">LOGIN</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </section>

    </main>

    <script src="assets/vendors/jquery/jquery.min.js"></script>
    <script src="assets/vendors/popper.js/popper.min.js"></script>
    <script src="assets/vendors/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/vendors/bootstrap-select/js/bootstrap-select.min.js"></script>
    <script src="assets/vendors/jquery-scrollbar/jquery.scrollbar.min.js"></script>
    <script src="assets/vendors/jquery-scrollLock/jquery-scrollLock.min.js"></script>

    <script src="assets/vendors/flot/jquery.flot.js"></script>
    <script src="assets/vendors/flot/jquery.flot.resize.js"></script>
    <script src="assets/vendors/flot.curvedlines/curvedLines.js"></script>
    <script src="assets/vendors/jqvmap/jquery.vmap.min.js"></script>
    <script src="assets/vendors/jqvmap/maps/jquery.vmap.world.js"></script>
    <script src="assets/vendors/easy-pie-chart/jquery.easypiechart.min.js"></script>
    <script src="assets/vendors/salvattore/salvattore.min.js"></script>
    <script src="assets/vendors/sparkline/jquery.sparkline.min.js"></script>
    <script src="assets/vendors/moment/moment.min.js"></script>
    <script src="assets/vendors/fullcalendar/fullcalendar.min.js"></script>
    
     <script src="assets/vendors/jquery-mask-plugin/jquery.mask.min.js"></script>
    <script src="assets/vendors/select2/js/select2.full.min.js"></script>
    <script src="assets/vendors/dropzone/dropzone.min.js"></script>
    <script src="assets/vendors/moment/moment.min.js"></script>
    <script src="assets/vendors/nouislider/nouislider.min.js"></script>
    <script src="assets/vendors/trumbowyg/trumbowyg.min.js"></script>
    <script src="assets/vendors/flatpickr/flatpickr.min.js"></script>
    <script src="assets/vendors/rateyo/jquery.rateyo.min.js"></script>
    <script src="assets/vendors/jquery-text-counter/textcounter.min.js"></script>
    <script src="assets/vendors/autosize/autosize.min.js"></script>
    <script src="assets/vendors/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>

    <!-- Charts and maps-->
    <script src="assets/demo/js/flot-charts/curved-line.js"></script>
    <script src="assets/demo/js/flot-charts/dynamic.js"></script>
    <script src="assets/demo/js/flot-charts/line.js"></script>
    <script src="assets/demo/js/flot-charts/chart-tooltips.js"></script>
    <script src="assets/demo/js/other-charts.js"></script>
    <script src="assets/demo/js/jqvmap.js"></script>
    
    <!--high chart-->
    <script src="https://code.highcharts.com/maps/highmaps.js"></script>
    <script src="https://code.highcharts.com/maps/modules/exporting.js"></script>

    <script src="assets/vendors/highcharts/highchart.js"></script>
    <script src="assets/vendors/highcharts/data.js"></script>
    <script src="assets/vendors/highcharts/drilldown.js"></script>
    <script src="assets/vendors/highcharts/exporting.js"></script>
    <script src="assets/vendors/highcharts/export-data.js"></script>
    <script src="assets/vendors/highcharts/accesibility.js"></script>
    <script src="assets/vendors/daterangepicker/daterangepicker.min.js"></script>
    <script src="assets/js/highcharts/bullet.js"></script>
    
    <!-- Vendors: Data tables -->
    <script src="assets/vendors/datatables/jquery.dataTables.min.js"></script>
    <script src="assets/vendors/datatables-buttons/dataTables.buttons.min.js"></script>
    <script src="assets/vendors/datatables-buttons/buttons.print.min.js"></script>
    <script src="assets/vendors/jszip/jszip.min.js"></script>
    <script src="assets/vendors/datatables-buttons/buttons.html5.min.js"></script>
    
    <script src="assets/js/highcharts/highcharts-more.js"></script>
    <script src="assets/js/highcharts/theme1.js"></script>
    <!--owl corousel-->
    <script src="assets/vendors/OwlCarousel/owl.carousel.min.js"></script>


    <!-- App functions and actions -->
     <script src="assets/js/wow.js"></script>
    <script src="assets/js/app.min.js"></script>
    <script src="assets/js/main.js"></script>

</body>

app/views/authentications/new.html.erb
<h1>New Authentication</h1>

<%= render 'form', authentication: @authentication %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>