config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  require "sidekiq-status/web"
  require "sidekiq/cron/web"
  # require "sidekiq/batch/web"

  mount Sidekiq::Web, at: "/sidekiq"
  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"

  resources :authentications
  resources :bookings
  resources :rooms

  get "login", to: "authentications#login", as: :login
  post "auth/login", to: "authentications#server_login"
  get "logout", to: "authentications#logout", as: :logout

  get "available_rooms", to: "rooms#available_rooms", as: :available_rooms
  get "occupied_rooms", to: "rooms#occupied_rooms", as: :occupied_rooms
  get "checkin", to: "rooms#check_in", as: :check_in
  post "server_checkin", to: "rooms#server_check_in"
  get "checkout", to: "rooms#check_out", as: :check_out
  get "bulk_checkin", to: "rooms#bulk_check_in", as: :bulk_check_in

  get "room_booking", to: "bookings#room_booking", as: :room_booking
  post "room_booking", to: "bookings#server_booking", as: :server_booking

  get "profile", to: "authentications#profile", as: :profile

  # reports routes
  get "bills_reports", to: "reports#bills_reports", as: :bills_reports
  get "checkin_reports", to: "reports#checkin_reports", as: :checkin_reports
  get "checkout_reports", to: "reports#checkout_reports", as: :checkout_reports
  get "transfers_reports", to: "reports#transfers_reports", as: :transfers_reports
  get "complaints_reports", to: "reports#complaints_reports", as: :complaints_reports
  get "accomodation_reports", to: "reports#accomodation_reports", as: :accomodation_reports
  get "resources_reports", to: "reports#resources_reports", as: :resources_reports

  # get "booking", to: "bookings#bookings"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "dashboards#index"
  get "/", to: "dashboards#index", as: :dashboard
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token
  before_action :current_user

  # GET /rooms or /rooms.json
  def index
    @current_user = current_user
    begin
      # get all rooms
      url = URI("https://bookinn.ngrok.io/rooms")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      request = Net::HTTP::Get.new(url)
      request["Authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body
      @response_rooms = JSON.parse(response.read_body)
    rescue => exception
      @rooms = {}
    else
      if @response_rooms["status"] == 200
        @rooms = @response_rooms["data"]
      elsif @response_rooms["status"] == 401
      elsif @response_rooms["status"] == 401
      end
    end
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    # console
    begin
      # get all rooms
      url = URI("http://bookinn.ngrok.io/rooms")

      http = Net::HTTP.new(url.host, url.port)
      request = Net::HTTP::Get.new(url)
      request["Authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body
      @response_rooms = JSON.parse(response.read_body)

      # get all room_types
      url = URI("http://bookinn.ngrok.io/room_types")

      http = Net::HTTP.new(url.host, url.port)
      request = Net::HTTP::Get.new(url)
      request["Authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body
      @response_room_types = JSON.parse(response.read_body)

      # get all hotels
      url = URI("http://bookinn.ngrok.io/hotels")

      http = Net::HTTP.new(url.host, url.port)
      request = Net::HTTP::Get.new(url)
      request["Authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body
      @response_hotels = JSON.parse(response.read_body)

      # get all hotel_wings
      url = URI("http://bookinn.ngrok.io/hotel_wings")

      http = Net::HTTP.new(url.host, url.port)
      request = Net::HTTP::Get.new(url)
      request["Authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body
      @response_hotel_wings = JSON.parse(response.read_body)
      # byebug
    rescue => exception
      @room_types = []
      @hotels = []
      @hotel_wings = []
      @rooms = []
      # byebug
    else
      if @response_room_types["status"] == 200 && @response_hotel_wings["status"] == 200 && @response_hotels["status"] == 200 && @response_rooms["status"] == 200
        @room_types = @response_room_types["data"]
        @hotels = @response_hotels["data"]
        @hotel_wings = @response_hotel_wings["data"]
        @rooms = @response_rooms["data"]
        # byebug
        # byebug
      elsif @response_room_types["status"] == 401
        # @room_types = []
        redirect_to login_path
      else
        @room_types = []
      end
    end
  end

  # GET /rooms/1/edit
  def edit
  end

  def check_in
    # console
    begin
      # get countries
      url = URI("https://bookinn.ngrok.io/countries")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(url)
      request["authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body

      @response_countries = JSON.parse(response.read_body)

      # get genders
      url = URI("https://bookinn.ngrok.io/gender")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(url)
      request["authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body

      @response_genders = JSON.parse(response.read_body)

      # get room amenities
      url = URI("https://bookinn.ngrok.io/room_amenities")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(url)
      request["authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body

      @response_room_amenities = JSON.parse(response.read_body)

      # get hotel amenities
      url = URI("https://bookinn.ngrok.io/hotel_amenities")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(url)
      request["authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body

      @response_hotel_amenities = JSON.parse(response.read_body)

      # get room types
      url = URI("https://bookinn.ngrok.io/room_types")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(url)
      request["authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body

      @response_room_types = JSON.parse(response.read_body)

      # get rooms
      url = URI("https://bookinn.ngrok.io/rooms")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(url)
      request["authorization"] = "Bearer #{session["access_token"]}"

      response = http.request(request)
      puts response.read_body

      @response_rooms = JSON.parse(response.read_body)
    rescue => exception
      @countries = []
      @genders = []
      @room_amenities = []
      @hotel_amenities = []
      @room_types = []
      @rooms = []
    else
      if @response_countries["status"] == 200 && @response_genders["status"] == 200 && @response_room_amenities["status"] == 200 && @response_hotel_amenities["status"] == 200 && @response_room_types["status"] == 200 && @response_rooms["status"] == 200
        @countries = @response_countries["data"]
        @genders = @response_genders["data"]
        @room_amenities = @response_room_amenities["data"]
        @hotel_amenities = @response_hotel_amenities["data"]
        @room_types = @response_room_types["data"]
        @rooms = @response_rooms["data"]
        # byebug
      else
      end
    end
  end

  def server_check_in
    begin
      puts params
      url = URI("https://bookinn.ngrok.io/single_direct_check_in")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Post.new(url)
      request["Content-Type"] = "application/json"
      request["Authorization"] = "Bearer #{session["access_token"]}"
      request.body = params.to_json
      response = http.request(request)
      puts response.read_body

      @response_json = JSON.parse(response.read_body)
    rescue Net::ReadTimeout
      puts "endpoint timed out"
    rescue ActiveRecord::RecordNotFound
    else
      if @response_json["status"] == 200
        # create session
        session["user_id"] = @response_json["data"]["id"]
        session["access_token"] = @response_json["access_token"]
        session["username"] = @response_json["data"]["username"]
        session["role_id"] = @response_json["data"]["role_id"]
        session["hotel_id"] = @response_json["data"]["hotel_id"]
        session["email"] = @response_json["data"]["email"]
        redirect_to dashboard_path
      else
        # login failed
        redirect_to login_path
      end
    end
  end

  def check_out
  end

  def bulk_check_in
  end

  # available rooms
  def available_rooms
    begin
      url = URI("https://bookinn.ngrok.io/room/status")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Post.new(url)
      request["Authorization"] = "Bearer #{session["access_token"]}"
      form_data = [["status", "1"]]
      request.set_form form_data, "multipart/form-data"
      # byebug
      response = http.request(request)
      puts response.read_body
      @response_json = JSON.parse(response.read_body)
      # byebug

    rescue => exception
      # byebug
      puts exception
      @rooms = Array.new
    else
      # byebug
      if @response_json["status"] == 200
        # success
        @rooms = @response_json["data"]
      elsif @response_json["status"] == 404
        # error
        # show error page
        @rooms = []
      elsif @response_json["status"] == 401
        redirect_to login_path
      else
        @rooms = []
      end
    end
  end

  # occupied rooms
  def occupied_rooms
    begin
      url = URI("https://bookinn.ngrok.io/room/status")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Post.new(url)
      request["Authorization"] = "Bearer #{session["access_token"]}"
      form_data = [["status", "2"]]
      request.set_form form_data, "multipart/form-data"
      # byebug
      response = http.request(request)
      puts response.read_body
      @response_json = JSON.parse(response.read_body)
      # byebug

    rescue => exception
      # byebug
      @rooms = Array.new
    else
      # byebug
      if @response_json["status"] == 200
        # success
        @rooms = @response_json["data"]
      elsif @response_json["status"] == 404
        # error
        # show error page
        @rooms = []
      elsif @response_json["status"] == 401
        redirect_to login_path
      else
        @rooms = []
      end
    end
  end

  # POST /rooms or /rooms.json
  def create
    begin
      url = URI("https://bookinn.ngrok.io/rooms")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      request = Net::HTTP::Post.new(url)
      request["Authorization"] = "Bearer #{session["access_token"]}"
      request["Content-Type"] = "application/json"
      request.body = room_params.to_json
      response = http.request(request)

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hotel_id %>
    <%= form.text_field :hotel_id %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div>

  <div class="field">
    <%= form.label :room_no %>
    <%= form.text_field :room_no %>
  </div>

  <div class="field">
    <%= form.label :room_name %>
    <%= form.text_field :room_name %>
  </div>

  <div class="field">
    <%= form.label :room_type_id %>
    <%= form.text_field :room_type_id %>
  </div>

  <div class="field">
    <%= form.label :room_price %>
    <%= form.text_field :room_price %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.text_field :capacity %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.text_field :is_active %>
  </div>

  <div class="field">
    <%= form.label :created_by %>
    <%= form.text_field :created_by %>
  </div>

  <div class="field">
    <%= form.label :updated_by %>
    <%= form.text_field :updated_by %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/available_rooms.html.erb
<!DOCTYPE html>
<html lang="en">
    
<!-- Mirrored from byrushan.com/projects/material-admin/app/2.6/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 26 Jul 2020 11:34:03 GMT -->
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
		<link rel='icon' href='demo/img/.png' type='image/x-icon'/ >
		<title>Reception Desk</title>

		<!-- icon fonts -->

		<link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_1.css">
		<link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_2.css">
		<link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_3.css">
		<link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_4.css">
		<link rel="stylesheet" href="http://cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css">

		<!-- Vendor styles -->
		<link rel="stylesheet" href="assets/vendors/OwlCarousel/assets/owl.carousel.min.css">
		<link rel="stylesheet" href="assets/vendors/OwlCarousel/assets/owl.theme.default.css">
		<link rel="stylesheet" href="assets/css/flaticon-font/flaticon.css">

        <link rel="stylesheet" href="assets/vendors/material-design-iconic-font/css/material-design-iconic-font.min.css">
        <link rel="stylesheet" href="assets/vendors/animate.css/animate.min.css">
        <link rel="stylesheet" href="assets/vendors/jquery-scrollbar/jquery.scrollbar.css">
        <link rel="stylesheet" href="assets/vendors/fullcalendar/fullcalendar.min.css">
        <link rel="stylesheet" href="assets/vendors/select2/css/select2.min.css">
        <link rel="stylesheet" href="assets/vendors/bootstrap-select/css/bootstrap-select.min.css">
        <link rel="stylesheet" href="assets/vendors/dropzone/dropzone.css">
        <link rel="stylesheet" href="assets/vendors/nouislider/nouislider.min.css">
        <link rel="stylesheet" href="assets/vendors/trumbowyg/ui/trumbowyg.min.css">
        <link rel="stylesheet" href="assets/vendors/flatpickr/flatpickr.min.css" />
        <link rel="stylesheet" href="assets/vendors/rateyo/jquery.rateyo.min.css">
        <link rel="stylesheet" href="assets/vendors/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">

        <!-- App styles -->
		<link rel="stylesheet" href="assets/css/app.min.css">
		<link rel="stylesheet" href="assets/css/daterangepicker.css">
	
    </head>

    <body data-ma-theme="green">
        <main class="main">
            <%= render "layouts/page_loader" %>

            <%= render "layouts/page_header" %>
            
			<%= render "layouts/page_sidebar" %>
			

                    <!-- unfreeze account -->
        <div class="modal fade" id="deactivate-room" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Deactivate Room 104</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <div class="">
                            <h5>Are you sure you want to deactivate this room?</h5>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Reason<strong class="text-danger">*</strong></label>
                                    <textarea class="form-control validate"  minlength="2" placeholder="Enter reason for room deactivation" required></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-success">Yes, Deactivate Room</button>
                    </div>
                </div>
            </div>
        </div>
            
            
			 <section class="content">
                <header class="content__title px-0 border-0">                    
				 	<div class="row">
						<div class="col-lg-6 col-sm-12 col-md-6">
							<span class="rev-title-container">
							 <h1 class="text-capitalize stream_name m-0">Available Rooms</h1>
							</span>
							<div class="">
								<ol class="breadcrumb border-0">
                                    <li class="breadcrumb-item">Home</li>
                                    <li class="breadcrumb-item">Rooms</li>
									<li class="breadcrumb-item active">Available Rooms</li>
								
								</ol>
								
							</div>
                        </div>
                        <div class="col-lg-6 col-sm-12 col-md-6">
                            <a></a>
                        </div>

					</div>
                </header>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-hover table-striped spacing8" id="data-table">
                                        <thead>
                                            <tr> 
                                                <th>ID </th>
                                                <th>Room No.</th>
                                                <th>Room Type</th>
                                                <th>Date Created</th>
                                                <th>Last Occupied</th>
                                                <th>Created by</th>
                                                
                                                <th>Actions</th>

                                            </tr>
                                        </thead>

                                        <tbody>
                                            <%= render partial: "datatables/partials/available_rooms" %>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                   
			
                <footer class="footer hidden-xs-down">
                    <p>A product of Nouveta</p>
                </footer>
            </section>
        </main>

        <!-- Older IE warning message -->
            <!--[if IE]>
                <div class="ie-warning">
                    <h1>Warning!!</h1>
                    <p>You are using an outdated version of Internet Explorer, please upgrade to any of the following web browsers to access this website.</p>

                    <div class="ie-warning__downloads">
                        <a href="http://www.google.com/chrome">
                            <img src="img/browsers/chrome.png" alt="">
                        </a>

                        <a href="https://www.mozilla.org/en-US/firefox/new">
                            <img src="img/browsers/firefox.png" alt="">
                        </a>

                        <a href="http://www.opera.com">
                            <img src="img/browsers/opera.png" alt="">
                        </a>

                        <a href="https://support.apple.com/downloads/safari">
                            <img src="img/browsers/safari.png" alt="">
                        </a>

                        <a href="https://www.microsoft.com/en-us/windows/microsoft-edge">
                            <img src="img/browsers/edge.png" alt="">
                        </a>

                        <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                            <img src="img/browsers/ie.png" alt="">
                        </a>
                    </div>
                    <p>Sorry for the inconvenience!</p>
                </div>
            <![endif]-->

        <!-- Javascript -->
        <!-- Vendors -->
        <script src="assets/vendors/jquery/jquery.min.js"></script>
        <script src="assets/vendors/popper.js/popper.min.js"></script>
        <script src="assets/vendors/bootstrap/js/bootstrap.min.js"></script>
        <script src="assets/vendors/bootstrap-select/js/bootstrap-select.min.js"></script>
        <script src="assets/vendors/jquery-scrollbar/jquery.scrollbar.min.js"></script>
        <script src="assets/vendors/jquery-scrollLock/jquery-scrollLock.min.js"></script>

        <script src="assets/vendors/flot/jquery.flot.js"></script>
        <script src="assets/vendors/flot/jquery.flot.resize.js"></script>
        <script src="assets/vendors/flot.curvedlines/curvedLines.js"></script>
        <script src="assets/vendors/jqvmap/jquery.vmap.min.js"></script>
        <script src="assets/vendors/jqvmap/maps/jquery.vmap.world.js"></script>
        <script src="assets/vendors/easy-pie-chart/jquery.easypiechart.min.js"></script>
        <script src="assets/vendors/salvattore/salvattore.min.js"></script>
        <script src="assets/vendors/sparkline/jquery.sparkline.min.js"></script>
        <script src="assets/vendors/moment/moment.min.js"></script>
        <script src="assets/vendors/fullcalendar/fullcalendar.min.js"></script>
		
		 <script src="assets/vendors/jquery-mask-plugin/jquery.mask.min.js"></script>
        <script src="assets/vendors/select2/js/select2.full.min.js"></script>
        <script src="assets/vendors/dropzone/dropzone.min.js"></script>
        <script src="assets/vendors/moment/moment.min.js"></script>
        <script src="assets/vendors/nouislider/nouislider.min.js"></script>
        <script src="assets/vendors/trumbowyg/trumbowyg.min.js"></script>
        <script src="assets/vendors/flatpickr/flatpickr.min.js"></script>
        <script src="assets/vendors/rateyo/jquery.rateyo.min.js"></script>
        <script src="assets/vendors/jquery-text-counter/textcounter.min.js"></script>
        <script src="assets/vendors/autosize/autosize.min.js"></script>
        <script src="assets/vendors/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>

        <!-- Charts and maps-->
        <script src="assets/demo/js/flot-charts/curved-line.js"></script>
        <script src="assets/demo/js/flot-charts/dynamic.js"></script>
        <script src="assets/demo/js/flot-charts/line.js"></script>
        <script src="assets/demo/js/flot-charts/chart-tooltips.js"></script>
        <script src="assets/demo/js/other-charts.js"></script>
        <script src="assets/demo/js/jqvmap.js"></script>
		
		<!--high chart-->
		<script src="https://code.highcharts.com/maps/highmaps.js"></script>
		<script src="https://code.highcharts.com/maps/modules/exporting.js"></script>

		<script src="assets/vendors/highcharts/highchart.js"></script>
		<script src="assets/vendors/highcharts/data.js"></script>
		<script src="assets/vendors/highcharts/drilldown.js"></script>
		<script src="assets/vendors/highcharts/exporting.js"></script>
		<script src="assets/vendors/highcharts/export-data.js"></script>
		<script src="assets/vendors/highcharts/accesibility.js"></script>
		<script src="assets/vendors/daterangepicker/daterangepicker.min.js"></script>
        <script src="assets/js/highcharts/bullet.js"></script>
        
        <!-- Vendors: Data tables -->
        <script src="assets/vendors/datatables/jquery.dataTables.min.js"></script>
        <script src="assets/vendors/datatables-buttons/dataTables.buttons.min.js"></script>
        <script src="assets/vendors/datatables-buttons/buttons.print.min.js"></script>
        <script src="assets/vendors/jszip/jszip.min.js"></script>
        <script src="assets/vendors/datatables-buttons/buttons.html5.min.js"></script>
		
		<script src="assets/js/highcharts/highcharts-more.js"></script>
		<script src="assets/js/highcharts/theme1.js"></script>
		<!--owl corousel-->
		<script src="assets/vendors/OwlCarousel/owl.carousel.min.js"></script>


        <!-- App functions and actions -->
     	<script src="assets/js/wow.js"></script>
        <script src="assets/js/app.min.js"></script>
        <script src="assets/js/main.js"></script>
					
        <script src="assets/js/chart-data/revenue-targets.js"></script>
        <script src="assets/js/chart-data/revenue-streams.js"></script>
		 <script src="assets/js/chart-data/revenue-by-bank.js"></script>
        <script src="assets/js/chart-data/revenue-collected.js"></script>
		<script src="assets/js/chart-data/perfomance.js"></script>
        <script src="assets/js/chart-data/hourly-revenue-collection.js"></script>
		
	
		<!--map scripts-->
		
		<script src="assets/js/chart-data/map-data.js"></script>
		
       
		
		
		
    </body>

<!-- Mirrored from byrushan.com/projects/material-admin/app/2.6/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 26 Jul 2020 11:34:43 GMT -->
</html>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hotel:</strong>
  <%= @room.hotel_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @room.room_id %>
</p>

<p>
  <strong>Room no:</strong>
  <%= @room.room_no %>
</p>

<p>
  <strong>Room name:</strong>
  <%= @room.room_name %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @room.room_type_id %>
</p>

<p>
  <strong>Room price:</strong>
  <%= @room.room_price %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @room.capacity %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @room.is_active %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @room.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @room.updated_by %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>