config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  require "sidekiq-status/web"
  require "sidekiq/cron/web"
  # require "sidekiq/batch/web"

  mount Sidekiq::Web, at: "/sidekiq"
  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"

  resources :authentications
  resources :bookings
  resources :rooms

  get "login", to: "authentications#login", as: :login
  post "auth/login", to: "authentications#server_login"
  get "logout", to: "authentications#logout", as: :logout

  get "available_rooms", to: "rooms#available_rooms", as: :available_rooms
  get "occupied_rooms", to: "rooms#occupied_rooms", as: :occupied_rooms
  get "checkin", to: "rooms#check_in", as: :check_in
  post "server_checkin", to: "rooms#server_check_in"
  get "checkout", to: "rooms#check_out", as: :check_out
  get "bulk_checkin", to: "rooms#bulk_check_in", as: :bulk_check_in

  get "room_booking", to: "bookings#room_booking", as: :room_booking
  post "room_booking", to: "bookings#server_booking", as: :server_booking

  get "profile", to: "authentications#profile", as: :profile

  # reports routes
  get "bills_reports", to: "reports#bills_reports", as: :bills_reports
  get "checkin_reports", to: "reports#checkin_reports", as: :checkin_reports
  get "checkout_reports", to: "reports#checkout_reports", as: :checkout_reports
  get "transfers_reports", to: "reports#transfers_reports", as: :transfers_reports
  get "complaints_reports", to: "reports#complaints_reports", as: :complaints_reports
  get "accomodation_reports", to: "reports#accomodation_reports", as: :accomodation_reports
  get "resources_reports", to: "reports#resources_reports", as: :resources_reports

  # get "booking", to: "bookings#bookings"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "dashboards#index"
  get "/", to: "dashboards#index", as: :dashboard
end

app/views/layouts/_page_header.html.erb
<header class="header">
    <div class="navigation-trigger hidden-xl-up" data-ma-action="aside-open" data-ma-target=".sidebar">
        <div class="navigation-trigger__inner">
            <i class="navigation-trigger__line"></i>
            <i class="navigation-trigger__line"></i>
            <i class="navigation-trigger__line"></i>
        </div>
    </div>
    <div class="header__logo hidden-sm-down">
        <a class="" href="index.html"><%= image_tag "bookinn.png", class: "the-logo" %></a>

        
        <h1>
            <a class="mb-0 text-capitalize font-12">Reception Desk Portal</a>
        </h1>
    </div>
    <form class="search">
        <div class="search__inner">
            <input type="text" class="search__text" placeholder="Search site">
            <i class="zmdi zmdi-search search__helper" data-ma-action="search-close"></i>
        </div>
    </form>
    
    <ul class="top-nav">
        <li class="hidden-xl-up"><a href="#" data-ma-action="search-open"><i class="zmdi zmdi-search"></i></a></li>
        
        <li data-toggle="tooltip" data-original-title="Time logged in" class=" top-nav__notifications p-0 m-0">
            <a href="#" data-toggle="dropdown"  class="top-nav__notify min-width-15px" >
                <i class="zmdi zmdi-time"></i>
            </a>
            
        </li>
        
        <li data-toggle="tooltip" data-original-title="Time logged in " class="">
            <a href="#" data-toggle="dropdown"  class="" >
                3 min
            </a>
            
        </li>
        
        <li class="ml-5" >
            <a href="new-parent.html" data-toggle="tooltip" data-original-title="Tasks completed" >
                <i class="mdi mdi-pulse"></i><span class="mx-3">22</span>
            </a>
        </li>
    </ul>

    
</header>

app/views/layouts/_page_loader.html.erb
<div class="page-loader">
    <div class="page-loader__spinner">
        <svg viewBox="25 25 50 50">
            <circle cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <span class="powerd-container">
        <strong>A product of</strong>
        <%= image_tag "nouveta_logo.png" %>
    </span>
</div>

app/views/layouts/_page_sidebar.html.erb
<aside class="sidebar">
    <div class="scrollbar-inner">
        <div class="user">
            <div class="user__info" data-toggle="dropdown">
                <div class="avatar-char bg-warning text-black mr-3 font-weight-bold">JM</div>
                <div>
                    <div class="user__name"><%= session["username"] %></div>
                    <div class="user__email"><%= session["email"] %></div>
                </div>
            </div>

            <div class="dropdown-menu">
                <a class="dropdown-item" href="my-profile.html">View Profile</a>
                <a class="dropdown-item d-none" href="#">Settings</a>
                <a class="dropdown-item" href="landing-page.html">Logout</a>
            </div>
        </div>

        <ul class="navigation">
            <li class="navigation__active">
            <%= link_to dashboard_path do %>
                <i
                    class="flaticon-bar-chart"></i>Dashboard
            <% end %>
            
            </li>

            <li class="navigation__sub">
                <a href="#"><i class="mdi mdi-cash"></i>Payment edits<i class="zmdi zmdi-caret-down drop-down-icon"></i></a>
                <ul>
                    <li><a href="reversal.html"><i class="flaticon-undo mr-2"></i>Reversals</a></li>
                    <li><a href="transfers.html"><i class="flaticon-transfer mr-2"></i>Transfers</a></li>
                    <li><a href=""><i class="zmdi zmdi-edit mr-2"></i>Non Cash Edits</a></li>
                </ul>
            </li>
            <li class="navigation__sub">
                <a href="#"><i class="mdi mdi-room-service-outline"></i>Rooms<i class="zmdi zmdi-caret-down drop-down-icon"></i></a>
                <ul>

                    <li>
                        <%= link_to check_in_path do %>
                            <i class="mdi mdi-account-plus-outline"></i>Check In
                        <% end %>
                    </li>
                    <li>
                        <%= link_to check_out_path do %>
                            <i class="mdi mdi-account-minus-outline"></i>Check Out
                        <% end %>
                    </li>
                    
                     <li>
                        <%= link_to room_booking_path do %>
                            <i class="mdi mdi-account-edit-outline"></i>Booking Room
                        <% end %>
                    </li>
                    
                    <li>
                        <%= link_to available_rooms_path do %>
                            <i class="mdi mdi-account-check-outline"></i>Available Rooms
                        <% end %>

                    </li>
                    <li>
                     <%= link_to occupied_rooms_path do %>
                            <i class="mdi mdi-account-cash-outline"></i>Occupied Rooms
                        <% end %>
                   </li>
                    <li><a href="restaurant/unavailable_rooms.html"><i class="mdi mdi-account-cancel-outline"></i>Unavailable Rooms</a></li>
                    <li>
                        <%= link_to bookings_path do %>
                            <i class="mdi mdi-account-group-outline"></i>Room Bookings
                        <% end %>
                    </li>

                </ul>
            </li>
            <li class="navigation__sub">
                <a href="#"><i class="mdi mdi-washing-machine"></i>Laundry<i class="zmdi zmdi-caret-down drop-down-icon"></i></a>
                <ul>
                    <li><a href="restaurant/laundry/laundry-packages.html"><i class="mdi mdi-washing-machine"></i>Laundry Packages</a></li>
                    <li><a href="restaurant/laundry/pending-laundry.html"><i class="mdi mdi-washing-machine-alert"></i>Pending Laundry</a></li>
                    <li><a href="restaurant/laundry/done-laundry.html"><i class="mdi mdi-dishwasher"></i>Done Laundry</a></li>
                </ul>
            </li>
            <li class="navigation__sub">
                <a href="#"><i class="mdi mdi-television"></i>Amenities<i class="zmdi zmdi-caret-down drop-down-icon"></i></a>
                <ul>
                    <li><a href="restaurant/amenities/room-amenities.html"><i class="mdi mdi-television-guide"></i>Room Amenitites</a></li>
                    <li><a href="restaurant/amenities/hotel-amenities.html"><i class="mdi mdi-monitor-screenshot"></i>Hotel Amenities</a></li>
                </ul>
            </li>
            <li class="navigation__sub">
                <a href="#"><i class="mdi mdi-credit-card-multiple-outline"></i>Bills<i class="zmdi zmdi-caret-down drop-down-icon"></i></a>
                <ul>
                    <li><a href="reversal.html"><i class="flaticon-undo mr-2"></i>Reversals</a></li>
                    <li><a href="transfers.html"><i class="flaticon-transfer mr-2"></i>Transfers</a></li>
                    <li><a href=""><i class="zmdi zmdi-edit mr-2"></i>Non Cash Edits</a></li>
                </ul>
            </li>
                <li class="navigation__sub">
                <a href="#"><i class="flaticon-document-1"></i>Reports<i class="zmdi zmdi-caret-down drop-down-icon"></i></a>
                <ul>
                    <li>
                        <%= link_to bills_reports_path do %>
                            <i class="mdi mdi-file-document-multiple"></i>Bills
                        <% end %>
                    </li>
                    <li> 
                        <%= link_to checkin_reports_path do %>
                            <i class="mdi mdi-account-multiple-plus-outline"></i>Check In
                        <% end %>
                    </li>
                    <li>
                        <%= link_to checkout_reports_path do %>
                            <i class="mdi mdi-account-multiple-minus-outline"></i>Check Out
                        <% end %>
                    </li>
                    <li>
                        <%= link_to transfers_reports_path do %>
                            <i class="mdi mdi-account-convert-outline"></i>Transfers
                        <% end %>
                    </li>
                    <li>
                        <%= link_to complaints_reports_path do %>
                            <i class="mdi mdi-message-alert-outline"></i>Complaints
                        <% end %>
                    </li>
                    <li>
                        <%= link_to accomodation_reports_path do %>
                            <i class="mdi mdi-room-service"></i>Accomodation
                        <% end %>
                    </li>
                    <li>
                        <%= link_to resources_reports_path do %>
                            <i class="mdi mdi-checkbox-multiple-blank-circle-outline"></i>Resources
                        <% end %>
                    </li>                    
                </ul>
            </li>
            
            <li class="navigation__sub">
                <a href="#"><i class="flaticon-user-2"></i>My Account <i class="zmdi zmdi-caret-down drop-down-icon pt-0"></i></a>
                <ul>
                    <li>
                        <%= link_to profile_path do %>
                            <i class="pe-7s-id mr-2"></i>My profile
                        <% end %>
                    </li>
                    <li><a href="account-logs.html"><i class="icon_hourglass mr-2"></i>Account Logs</a></li>
                    <li><a href="deligate.html"><i class="pe-7s-portfolio mr-2"></i>Delegate role</a></li>
                    <li><a href="my-delegations.html"><i class="zmdi zmdi-case-check mr-2"></i>My Delegations</a></li>
                    <li><a href="password.html"><i class="flaticon-forgot mr-2"></i>Change password</a></li>
                    
                </ul>
            </li>
            
                <li class="navigation__sub d-none">
                <a href="#"><i class="flaticon-friends"></i>User Accounts  <i class="zmdi zmdi-caret-down drop-down-icon pt-0"></i></a>
                <ul>
                    <li><a href="new-user.html"><i class="flaticon-add-user mr-2"></i>New user</a></li>
                    <li><a href="active-users.html"><i class="zmdi zmdi-check-all"></i>Active users</a></li>
                    <li><a href="blocked-users.html"><i class="zmdi zmdi-block"></i>Inactive users</a></li>
                    <li><a href="user-management.html"><i class="zmdi zmdi-settings mr-2"></i>User Management</a></li>
                    
                </ul>
            </li>
            
            <li class="navigation__sub">
                <a href="#"><i class="ti-settings"></i>Setup<i class="zmdi zmdi-caret-down drop-down-icon pt-0"></i></a>
                <ul>
                    <li><a href="restaurant/setup/general-setup.html"><i class="mdi mdi-warehouse"></i>General Setup</a></li>
                    <li><a href="restaurant/setup/accomodation.html"><i class="mdi mdi-room-service"></i>Accomodation</a></li>
                    <li><a href="restaurant/setup/laundry.html"><i class="mdi mdi-washing-machine"></i>Laundry</a></li>
                    <li><a href="restaurant/setup/discounts.html"><i class="mdi mdi-cash-multiple"></i>Discounts</a></li>
                    <li><a href="restaurant/setup/amenities.html"><i class="mdi mdi-television"></i>Amenities</a></li>
                    <li>
                        <%= link_to new_room_path do %>
                            <i class="mdi mdi-room-service"></i>Rooms
                        <% end %>
                    </li>
                    <li><a href="restaurant/setup/drivers.html"><i class="mdi mdi-car-seat"></i>Drivers</a></li>
                    <li><a href="restaurant/setup/vehicle.html"><i class="mdi mdi-car-outline"></i>Vehicles</a></li>
                </ul>
            </li>
                <li class="navigation__active mt-4">
                 <%= link_to logout_path do %>
                    <i class="zmdi zmdi-power"></i> Logout
                <% end %>
                </li>
        </ul>
    </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- icon fonts -->

		<%# <link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_1.css">
		<link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_2.css">
		<link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_3.css">
		<link rel="stylesheet" href="assets/css/icon_fonts/css/icon_set_4.css">
		<link rel="stylesheet" href="http://cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css">

		<!-- Vendor styles -->
		<link rel="stylesheet" href="assets/vendors/OwlCarousel/assets/owl.carousel.min.css">
		<link rel="stylesheet" href="assets/vendors/OwlCarousel/assets/owl.theme.default.css">
		<link rel="stylesheet" href="assets/css/flaticon-font/flaticon.css">

        <link rel="stylesheet" href="assets/vendors/material-design-iconic-font/css/material-design-iconic-font.min.css">
        <link rel="stylesheet" href="assets/vendors/animate.css/animate.min.css">
        <link rel="stylesheet" href="assets/vendors/jquery-scrollbar/jquery.scrollbar.css">
        <link rel="stylesheet" href="assets/vendors/fullcalendar/fullcalendar.min.css">
        <link rel="stylesheet" href="assets/vendors/select2/css/select2.min.css">
        <!-- Not needed in dashboard -->
        <link rel="stylesheet" href="assets/vendors/bootstrap-select/css/bootstrap-select.min.css">
        <!-- end of not needed -->

        <link rel="stylesheet" href="assets/vendors/dropzone/dropzone.css">
        <link rel="stylesheet" href="assets/vendors/nouislider/nouislider.min.css">
        <link rel="stylesheet" href="assets/vendors/trumbowyg/ui/trumbowyg.min.css">
        <link rel="stylesheet" href="assets/vendors/flatpickr/flatpickr.min.css" />
        <link rel="stylesheet" href="assets/vendors/rateyo/jquery.rateyo.min.css">
        <link rel="stylesheet" href="assets/vendors/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">

        <!-- // Add the new slick-theme.css if you want the default styling  needed in dashboard-->
		<link rel="stylesheet" href="assets/vendors/slick/slick.css"/>
		<link rel="stylesheet" href="assets/vendors/slick/slick-theme.css"/>	

        <!-- App styles -->
		<link rel="stylesheet" href="assets/css/app.min.css">
		<link rel="stylesheet" href="assets/css/daterangepicker.css"> %>
	
    
  </head>

  <body>
    <%= yield %>
    <!-- Older IE warning message -->
            <!--[if IE]>
                <div class="ie-warning">
                    <h1>Warning!!</h1>
                    <p>You are using an outdated version of Internet Explorer, please upgrade to any of the following web browsers to access this website.</p>

                    <div class="ie-warning__downloads">
                        <a href="http://www.google.com/chrome">
                            <img src="img/browsers/chrome.png" alt="">
                        </a>

                        <a href="https://www.mozilla.org/en-US/firefox/new">
                            <img src="img/browsers/firefox.png" alt="">
                        </a>

                        <a href="http://www.opera.com">
                            <img src="img/browsers/opera.png" alt="">
                        </a>

                        <a href="https://support.apple.com/downloads/safari">
                            <img src="img/browsers/safari.png" alt="">
                        </a>

                        <a href="https://www.microsoft.com/en-us/windows/microsoft-edge">
                            <img src="img/browsers/edge.png" alt="">
                        </a>

                        <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                            <img src="img/browsers/ie.png" alt="">
                        </a>
                    </div>
                    <p>Sorry for the inconvenience!</p>
                </div>
            <![endif]-->

        <!-- Javascript -->
        <!-- Vendors -->
    <%# <script src="assets/vendors/jquery/jquery.min.js"></script>
            <!-- only needed in dashboard -->
            <script src="assets/vendors/slick/slick.min.js"></script>
            <!--end of only needed -->
        <script src="assets/vendors/popper.js/popper.min.js"></script>
        <script src="assets/vendors/bootstrap/js/bootstrap.min.js"></script>
        <!-- not needed in dashboard -->
        <script src="assets/vendors/bootstrap-select/js/bootstrap-select.min.js"></script>
        <!-- end of not needed -->
        <script src="assets/vendors/jquery-scrollbar/jquery.scrollbar.min.js"></script>
        <script src="assets/vendors/jquery-scrollLock/jquery-scrollLock.min.js"></script>

        <script src="assets/vendors/flot/jquery.flot.js"></script>
        <script src="assets/vendors/flot/jquery.flot.resize.js"></script>
        <script src="assets/vendors/flot.curvedlines/curvedLines.js"></script>
        <script src="assets/vendors/jqvmap/jquery.vmap.min.js"></script>
        <script src="assets/vendors/jqvmap/maps/jquery.vmap.world.js"></script>
        <script src="assets/vendors/easy-pie-chart/jquery.easypiechart.min.js"></script>
        <script src="assets/vendors/salvattore/salvattore.min.js"></script>
        <script src="assets/vendors/sparkline/jquery.sparkline.min.js"></script>
        <script src="assets/vendors/moment/moment.min.js"></script>
        <!-- needed in dashboard -->
        <script src="assets/vendors/daterangepicker/daterangepicker.min.js"></script>
        <!-- end of needed -->
        <script src="assets/vendors/fullcalendar/fullcalendar.min.js"></script>
		
		 <script src="assets/vendors/jquery-mask-plugin/jquery.mask.min.js"></script>
        <script src="assets/vendors/select2/js/select2.full.min.js"></script>
        <script src="assets/vendors/dropzone/dropzone.min.js"></script>
        <script src="assets/vendors/moment/moment.min.js"></script>
        <script src="assets/vendors/nouislider/nouislider.min.js"></script>
        <script src="assets/vendors/trumbowyg/trumbowyg.min.js"></script>
        <script src="assets/vendors/flatpickr/flatpickr.min.js"></script>
        <script src="assets/vendors/rateyo/jquery.rateyo.min.js"></script>
        <script src="assets/vendors/jquery-text-counter/textcounter.min.js"></script>
        <script src="assets/vendors/autosize/autosize.min.js"></script>
        <script src="assets/vendors/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>

        <!-- Charts and maps-->
        <script src="assets/demo/js/flot-charts/curved-line.js"></script>
        <script src="assets/demo/js/flot-charts/dynamic.js"></script>
        <script src="assets/demo/js/flot-charts/line.js"></script>
        <script src="assets/demo/js/flot-charts/chart-tooltips.js"></script>
        <script src="assets/demo/js/other-charts.js"></script>
        <script src="assets/demo/js/jqvmap.js"></script>
		
		<!--high chart-->
		<script src="https://code.highcharts.com/maps/highmaps.js"></script>
        <script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
        <!-- end of other highcharts -->
        
        <!-- Vendors: Data tables -->
        <script src="assets/vendors/datatables/jquery.dataTables.min.js"></script>
        <script src="assets/vendors/datatables-buttons/dataTables.buttons.min.js"></script>
        <script src="assets/vendors/datatables-buttons/buttons.print.min.js"></script>
        <script src="assets/vendors/jszip/jszip.min.js"></script>
        <script src="assets/vendors/datatables-buttons/buttons.html5.min.js"></script>
        <!-- end of datatables -->

        <!-- high charts -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/highcharts.js" integrity="sha512-PpL09bLaSaj5IzGNx6hsnjiIeLm9bL7Q9BB4pkhEvQSbmI0og5Sr/s7Ns/Ax4/jDrggGLdHfa9IbsvpnmoZYFA==" crossorigin="anonymous"></script>
		<!-- <script src="assets/libs/highcharts/highchart.js"></script> -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/modules/data.min.js" integrity="sha512-z2pVXf6Q3w/tD7NnbA/u/EDW7X8VUISARx3mVRk0vGULcDRcfhA65veFZS3LWW3DM8l/MW2Oxu8PlqJa+Za4Hw==" crossorigin="anonymous"></script>    
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/modules/drilldown.min.js" integrity="sha512-1F5YJc0seERSBvoF3csYQm+JO6qF9O+1hwUKBbOUKcRj3RnDAmKEEzuqPnCcLOtt/2h2CzsCbSy0bv0yuCfZNQ==" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/modules/exporting.min.js" integrity="sha512-DuFO4JhOrZK4Zz+4K0nXseP0K/daLNCrbGjSkRzK+Zibkblwqc0BYBQ1sTN7mC4Kg6vNqr8eMZwLgTcnKXF8mg==" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/modules/offline-exporting.min.js" integrity="sha512-5vKhOIyF4HBeTJQ4VvTAWGuAvGMp3BbDwD6CjzZPc0T/h4D8bqvvj+D/IYyJ1ua6s72VcuQ2fPEjBn+CHR6UWQ==" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/modules/export-data.min.js" integrity="sha512-JFLRyhQGrSpOOboAjCGEfEm0Z+GvPcucULDdEhRFoGtJJ439x64z/F1f6GTJM7+3PGqXqgkXNc6LO/04RGsW4w==" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/modules/accessibility.min.js" integrity="sha512-cN9FFspkIN+ZS37xvtrtP4jfDc7D1BA1ma9l2YPkV47Ac70t98RjOe9gR+2dCBUkiyamLLfFtqXH+/iL0fqhjw==" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/es-modules/Series/ItemSeries.min.js" integrity="sha512-UnnyAAfaraMnJOILh+bwawPvAF4+bbOXAPcUv2OREvyYTdi8TPJ4UZ+Ip8IL3mMY+cAY/yzuzq+v/EvmoZx7iA==" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/modules/streamgraph.min.js" integrity="sha512-RjmbiCs5aaU692OGy4q5YbGnHmiGexQY54rMmsY2HbaHX6OJ5AxqAtDQ9lVGubnbz+UPanupAF3avZJKY2jNWg==" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/modules/series-label.min.js" integrity="sha512-ppfBb+ms2RL9FloNCD8c9mykruT6sI5ACsAdSgS69pDv/Dnn64LGewhmLnMVTCm3Zt5K2LXamZD4Ndr9EFUhMQ==" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/modules/annotations.min.js" integrity="sha512-Qq+ClgMyYirIBC34w/LXcHhviIf+DvBzPW7vi3Ekn/jHYArYe+6TCiFp74q7pkUEitJLF543JCgxVQ6ax4xBNg==" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/8.2.2/modules/bullet.min.js" integrity="sha512-RsB4WtWGLsMOVX4LGEqcG7TQHJBvD/wPgSYrN4zQUSvCzhubwAlxeXgFM1+ROQ7TzKfl0L6AbiBNXyRDBFKNoA==" crossorigin="anonymous"></script>
		<%# <script src="js/highcharts/theme1.js"></script> %>

		<%# <script src="https://code.highcharts.com/highcharts.js"></script>
		<script src="https://code.highcharts.com/modules/data.js"></script>
		<script src="https://code.highcharts.com/modules/drilldown.js"></script>
		<script src="https://code.highcharts.com/modules/exporting.js"></script>
		<script src="https://code.highcharts.com/modules/export-data.js"></script>
		<script src="https://code.highcharts.com/modules/accessibility.js"></script>

        <!-- high chart data -->
		<script src="assets/js/chart-data/all-bookinns.js"></script>
		<script src="assets/js/chart-data/bookinnBreakdown.js"></script>
		<script src="assets/js/chart-data/booking_summary.js"></script>
		<script src="assets/js/chart-data/active-branches.js"></script>
		<script src="assets/js/chart-data/perfomance.js"></script>
		<script src="assets/js/chart-data/ongoing-loans.js"></script>
		<script src="assets/js/chart-data/transaction-data.js"></script>
		<script src="assets/js/chart-data/members-activity.js"></script>
		<script src="assets/js/chart-data/column-member-activity.js"></script>
		<script src="assets/js/chart-data/transaction-activity.js"></script>

		<script src="assets/js/chart-data/thisMonthBookingPerfomance.js"></script>
        <!-- end of highcgarts for dashboard -->

		<script src="assets/vendors/highcharts/highchart.js"></script>
		<script src="assets/vendors/highcharts/data.js"></script>
		<script src="assets/vendors/highcharts/drilldown.js"></script>
		<script src="assets/vendors/highcharts/exporting.js"></script>
		<script src="assets/vendors/highcharts/export-data.js"></script>
		<script src="assets/vendors/highcharts/accesibility.js"></script>
		<script src="assets/vendors/daterangepicker/daterangepicker.min.js"></script>
		<script src="assets/js/highcharts/bullet.js"></script>
		
		<script src="assets/js/highcharts/highcharts-more.js"></script>
		<script src="assets/js/highcharts/theme1.js"></script>
		<!--owl corousel-->
		<script src="assets/vendors/OwlCarousel/owl.carousel.min.js"></script>


        <!-- App functions and actions -->
     	<script src="assets/js/wow.js"></script>
        <script src="assets/js/app.min.js"></script>
        <script src="assets/js/main.js"></script>
					
        <script src="assets/js/chart-data/revenue-targets.js"></script>
        <script src="assets/js/chart-data/revenue-streams.js"></script>
		 <script src="assets/js/chart-data/revenue-by-bank.js"></script>
        <script src="assets/js/chart-data/revenue-collected.js"></script>
		<script src="assets/js/chart-data/perfomance.js"></script>
        <script src="assets/js/chart-data/hourly-revenue-collection.js"></script>
		
	
		<!--map scripts-->
		
		<script src="assets/js/chart-data/map-data.js"></script>  %>
  </body>
</html>